// <auto-generated />
using FilmYonetimPaneli.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FilmYonetimPaneli.Persistence.Migrations
{
    [DbContext(typeof(FilmYonetimPaneliDbContext))]
    partial class FilmYonetimPaneliDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FilmSalon", b =>
                {
                    b.Property<int>("FilmsfilmID")
                        .HasColumnType("int");

                    b.Property<int>("SalonssalonID")
                        .HasColumnType("int");

                    b.HasKey("FilmsfilmID", "SalonssalonID");

                    b.HasIndex("SalonssalonID");

                    b.ToTable("FilmSalon");
                });

            modelBuilder.Entity("FilmYonetimPaneli.Domain.Entities.Film", b =>
                {
                    b.Property<int>("filmID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("filmID"));

                    b.Property<string>("filmAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("filmYapimYil")
                        .HasColumnType("int");

                    b.HasKey("filmID");

                    b.ToTable("Films");
                });

            modelBuilder.Entity("FilmYonetimPaneli.Domain.Entities.Salon", b =>
                {
                    b.Property<int>("salonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("salonID"));

                    b.Property<string>("salonAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("salonID");

                    b.ToTable("Salons");
                });

            modelBuilder.Entity("FilmSalon", b =>
                {
                    b.HasOne("FilmYonetimPaneli.Domain.Entities.Film", null)
                        .WithMany()
                        .HasForeignKey("FilmsfilmID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FilmYonetimPaneli.Domain.Entities.Salon", null)
                        .WithMany()
                        .HasForeignKey("SalonssalonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
